[tool.towncrier]
    package="eth_utils"
    filename = "docs/releases.rst"
    directory = "newsfragments"
    underlines = ["-", "~", "^"]
    title_format = "eth-utils v{version} ({project_date})"
    issue_format = "`#{issue} <https://github.com/ethereum/eth-utils/issues/{issue}>`__"
