blank_issues_enabled: true
contact_links:
<<<<<<< HEAD
  - name: Questions about using eth-utils?
=======
  - name: Questions about using <REPO_NAME>?
>>>>>>> template
    url: https://discord.gg/GHryRvPB84
    about: You can ask and answer usage questions on the Ethereum Python Community Discord
